Front/Controllers/ArticuloTiendaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Front.Controllers
{
    public class ArticuloTiendaController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            Entitys.Tienda tienda = new Entitys.Tienda();
            Entitys.Result result = Bussiness.Tienda.GetAll(tienda);
            if (result.Correct)
            {
                tienda.Tiendas = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(tienda);
        }

        [HttpGet]
        public ActionResult ArticuloTiendaAsignadas(int IdTienda)
        {
            Entitys.ArticuloTienda articuloTienda = new Entitys.ArticuloTienda();
            Entitys.Result result = Bussiness.ArticuloTienda.ArticuloTiendaAsignados(IdTienda);
            articuloTienda.Tienda = new Entitys.Tienda();
            articuloTienda.Articulo = new Entitys.Articulo();
            Entitys.Result result1 = Bussiness.Tienda.GetById(IdTienda);
            if (result.Correct && result1.Correct)
            {
                articuloTienda.ArticuloTiendas = result.Objects;
                articuloTienda.Tienda = (Entitys.Tienda)result1.Object;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(articuloTienda);
        }

        [HttpGet]
        public ActionResult ArticuloTiendaNoAsignadas(int IdTienda)
        {
            Entitys.ArticuloTienda articuloTienda = new Entitys.ArticuloTienda();
            Entitys.Result result = Bussiness.ArticuloTienda.ArticuloTiendaNoAsignados(IdTienda);
            articuloTienda.Tienda = new Entitys.Tienda();
            articuloTienda.Articulo = new Entitys.Articulo();
            Entitys.Result result1 = Bussiness.Tienda.GetById(IdTienda);
            if (result.Correct && result1.Correct)
            {
                articuloTienda.ArticuloTiendas = result.Objects;
                articuloTienda.Tienda = (Entitys.Tienda)result1.Object;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(articuloTienda);
        }

        [HttpPost]
        public ActionResult Add(int IdTienda, List<int> IdArticulo)
        {
            Entitys.ArticuloTienda articuloTienda = new Entitys.ArticuloTienda();
            Entitys.Result result = new Entitys.Result();
            if (articuloTienda != null)
            {
                foreach (var item in IdArticulo)
                {
                    result = Bussiness.ArticuloTienda.Add(IdTienda, item);
                }
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                    ViewBag.IdTienda = IdTienda;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                return Redirect("/ArticuloTienda/GetAll");
            }
            return PartialView("Modal");
        }

        public ActionResult Delete(int IdTienda, int IdArticulo)
        {
            Entitys.ArticuloTienda articuloTienda = new Entitys.ArticuloTienda();
            Entitys.Result result = Bussiness.ArticuloTienda.Delete(IdTienda,IdArticulo);
            if (articuloTienda != null)
            {
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                    ViewBag.IdTienda = IdTienda;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                return Redirect("/ArticuloTienda/GetAll");
            }
            return PartialView("Modal");
        }
    }
}

Front/Views/ArticuloTienda/ArticuloTiendaAsignadas.cshtml
@model Entitys.ArticuloTienda
@{
    ViewData["Title"] = "ArticuloTiendaAsignadas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2>Lista de Articulos de la tienda</h2>
    <hr />

    <div class="row">
        <div class="form-group">

            @Html.HiddenFor(model => model.Tienda.IdTienda)

        </div>

        <div style="float:left">
            <div class="col-5">
                @Html.LabelFor(model => model.Tienda.Sucursal, "Nombre de la tienda")

                @Html.TextBoxFor(model => model.Tienda.Sucursal, new { @class = "form-control", @ReadOnly="true" })
            </div>

        </div>

        <div style="float:right">
            @Html.ActionLink("Agregar", "ArticuloTiendaNoAsignadas", "ArticuloTienda", new { IdTienda = Model.Tienda.IdTienda }, htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
</div>

<div class="d-flex justify-content-around">
    <div class="row mt-5">
        <table class="table table-striped">
            <thead class="table-success">
                <tr>
                    <th style="display :none;">
                        IdArticulo
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Codigo
                    </th>
                    <th>
                        Descripcion
                    </th>
                    <th>
                        Precio
                    </th>
                    <th>
                        Imagen
                    </th>
                    <th>
                        Stock
                    </th>
                    <th>
                        Eliminar
                    </th>
                </tr>
            </thead>

            <tbody class="table-light">
                @foreach (Entitys.ArticuloTienda articuloTienda in Model.ArticuloTiendas)
                {
                    <tr>
                        <td style="display :none;">
                            @articuloTienda.Articulo.IdArticulo
                        </td>
                        <td>
                            @articuloTienda.Articulo.Nombre
                        </td>
                        <td>
                            @articuloTienda.Articulo.Codigo
                        </td>
                        <td>
                            @articuloTienda.Articulo.Descripcion
                        </td>
                        <td>
                            @articuloTienda.Articulo.Precio
                        </td>
                        <td>
                            @if (articuloTienda.Articulo.Imagen != null)
                            {
                                var imagenSRC = $"data:image;base64,{articuloTienda.Articulo.Imagen}";
                                <img src='@imagenSRC' height='150px' width='150px'>
                            }
                            else
                            {
                                <img src="~/Image/sin logo.jpg" height='150px' width='150px'>

                            }
                        </td>
                        <td>
                            @articuloTienda.Articulo.Stock
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger bi-trash" href="@Url.Action("Delete", "ArticuloTienda", new { IdTienda = articuloTienda.Tienda.IdTienda, IdArticulo = articuloTienda.Articulo.IdArticulo})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col col-lg-2">
            @Html.ActionLink("Regresar", "GetAll", "ArticuloTienda", htmlAttributes: new { @class = "btn btn-danger" })
        </div>
    </div>
</div>

Front/Views/ArticuloTienda/ArticuloTiendaNoAsignadas.cshtml
@model Entitys.ArticuloTienda
@{
    ViewData["Title"] = "ArticuloTiendaNoAsignadas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2>Lista de Articulos no asignados</h2>
    <hr />
    <div class="row">
        <div class="form-group">
            @Html.HiddenFor(model => model.Tienda.IdTienda)
        </div>

        <div style="float:left">
            <div class="col-5">
                @Html.LabelFor(model => model.Tienda.Sucursal, "Nombre de la tienda")

                @Html.TextBoxFor(model => model.Tienda.Sucursal, new { @class = "form-control", @ReadOnly="true" })
            </div>

        </div>    
    </div>
</div>
 @using (Html.BeginForm("Add", "ArticuloTienda", FormMethod.Post, new { enctype = "multipart/form-data", id = "form_materias" }))
 {
    <input id="IdTienda" name="IdTienda" type="hidden" value="@Model.Tienda.IdTienda">
    <div class="d-flex justify-content-around">
        <div class="row mt-5">
            <table class="table table-striped">
                <thead class="table-success">
                    <tr>
                        <th>
                            Seleccionar
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Codigo
                        </th>
                        <th>
                            Descripcion
                        </th>
                        <th>
                            Precio
                        </th>
                        <th>
                            Imagen
                        </th>
                        <th>
                            Stock
                        </th>
                    </tr>
                </thead>

                <tbody class="table-light">
                    @foreach (Entitys.ArticuloTienda articuloTienda in Model.ArticuloTiendas)
                    {
                        <tr>
                            <td>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="@articuloTienda.Articulo.IdArticulo" name="IdArticulo">
                                </div>
                            </td>
                            <td>
                                @articuloTienda.Articulo.Nombre
                            </td>
                            <td>
                                @articuloTienda.Articulo.Codigo
                            </td>
                            <td>
                                @articuloTienda.Articulo.Descripcion
                            </td>
                            <td>
                                @articuloTienda.Articulo.Precio
                            </td>
                            <td>
                                @if (articuloTienda.Articulo.Imagen != null)
                                {
                                    var imagenSRC = $"data:image;base64,{articuloTienda.Articulo.Imagen}";
                                    <img src='@imagenSRC' height='150px' width='150px'>
                                }
                                else
                                {
                                    <img src="~/Image/sin logo.jpg" height='150px' width='150px'>

                                }
                            </td>
                            <td>
                                @articuloTienda.Articulo.Stock
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col col-lg-2">
                <input type="submit" value="Guardar" class="btn btn-success" />
                @Html.ActionLink("Regresar", "ArticuloTiendaAsignadas", "ArticuloTienda", new { IdTienda = Model.Tienda.IdTienda }, htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

Front/Views/ArticuloTienda/GetAll.cshtml
@model Entitys.Tienda
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-5">
    <h2>Lista de Tiendas</h2>
    <hr />
</div>
<div class="d-flex justify-content-around">
    <div class="row mt-5">
        <table class="table table-striped" id="tblCliente">
            <thead class="table-success">
                <tr>
                    <th>
                        Articulos
                    </th>
                    <th style="display :none;">
                        IdTienda
                    </th>
                    <th>
                        Sucursal
                    </th>
                    <th>
                        Direccion
                    </th>
                </tr>
            </thead>

            <tbody class="table-light">
                @foreach (Entitys.Tienda tienda in Model.Tiendas)
                {
                    <tr>
                        <td class="text-center">
                            <a class="btn btn-primary" href="@Url.Action("ArticuloTiendaAsignadas", "ArticuloTienda", new { IdTienda = tienda.IdTienda})">Seleccionar</a>
                        </td>
                        <td style="display :none;">
                            @tienda.IdTienda
                        </td>
                        <td>
                            @tienda.Sucursal
                        </td>
                        <td>
                            @tienda.DireccionTienda.Calle @tienda.DireccionTienda.NumeroInterior @tienda.DireccionTienda.NumeroExterior @tienda.DireccionTienda.Colonia.Nombre @tienda.DireccionTienda.Colonia.CodigoPostal @tienda.DireccionTienda.Colonia.Municipio.Nombre @tienda.DireccionTienda.Colonia.Municipio.Estado.Pais.Nombre
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblCliente').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });

    </script>

}

Front/Views/ArticuloTienda/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer" data-bs-dismiss="modal">
                @Html.ActionLink("Regresar", "ArticuloTiendaAsignadas", "ArticuloTienda", new { IdTienda = ViewBag.IdTienda }, htmlAttributes: new { @class = "btn btn-success"})
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>